FROM python:latest

ENV PYTHONUNBUFFERED=1

WORKDIR /usr/src/app/consumer

COPY consumer/consumer.py .
COPY consumer/requirements.txt .
COPY recommendationapp ./recommendationapp

RUN pip install -r requirements.txt

CMD ["python", "consumer.py"]