version: "3.2"
services:
  recommendationapp:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: recommendationapp
    environment:
      AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    ports:
      - "5000:5000"

  rabbit_mq:
    # management image -> web dashboard
    image: rabbitmq:3.12.0-management
    container_name: rabbit_mq
    ports:
        - '5672:5672'
        - '15672:15672'
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data

  consumer1:
    build:
      dockerfile: Dockerfile_consumer
    depends_on:
        - rabbit_mq
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'

  consumer2:
    build:
      dockerfile: Dockerfile_consumer
    depends_on:
        - rabbit_mq
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'

volumes:
    rabbit_mqdata:
      driver: local