"""add odds table

Revision ID: 371d6d8a3604
Revises: 4082b9b48b6a
Create Date: 2023-06-19 18:43:27.277570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371d6d8a3604'
down_revision = '4082b9b48b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odds',
    sa.Column('odd_id', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=50), nullable=True),
    sa.Column('odds', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('odd_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('odds')
    # ### end Alembic commands ###
