"""change user_id to string

Revision ID: 55434422ed1e
Revises: 371d6d8a3604
Create Date: 2023-06-19 21:04:46.818639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55434422ed1e'
down_revision = '371d6d8a3604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
