"""created models

Revision ID: 735e91878a1a
Revises: 
Create Date: 2023-04-09 22:15:46.705449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735e91878a1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('begin_timestamp', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.Column('end_timestamp', sa.String(length=50), nullable=True),
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('league', sa.String(length=20), nullable=True),
    sa.Column('participants', sa.String(), nullable=True),
    sa.Column('sport', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('registration_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('coupons',
    sa.Column('coupon_id', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=50), nullable=True),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.Column('stake', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('coupon_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coupons')
    op.drop_table('users')
    op.drop_table('events')
    # ### end Alembic commands ###
